package org.mitre.emd;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

/**
 * Transforms an ASM generated byte array into a compiled class.
 */
public class Transformer {
    Transformer(){}

    public void writeClass(byte[] bytes, String className){
        String classLocation = "out/production/classes/org/mitre/emd/rules/";
        if(Path.of(classLocation).getParent().toString() != "emd"){  // TODO need to figure out how to make this work when packaged in a jar
            classLocation = "../emd/" + classLocation;
        }
        if (!Files.exists(Path.of(classLocation))){
            try {
                Files.createDirectories(Path.of(classLocation));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        try {
            Files.write(Paths.get(classLocation, className + ".class"), bytes, StandardOpenOption.CREATE);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
